In [10]:
import numpy as np

##### method-1

In [11]:
a = [1,2,3,4]
arr = np.array(a)

In [12]:
arr

array([1, 2, 3, 4])

##### method-2

In [13]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

#### taking user input

In [14]:
a=[]
n = int(input("enter the size of the array"))
for i in range(n):
    val=int(input("enter the num :"))
    a.append(val)
my_arr = np.array(a)
my_arr

enter the size of the array5
enter the num :1
enter the num :2
enter the num :4
enter the num :5
enter the num :6


array([1, 2, 4, 5, 6])