In [1]:
import numpy as np


In [6]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [3]:
a*2

array([2, 4, 6, 8])

In [4]:
a+2

array([3, 4, 5, 6])

In [7]:
a**4

array([  1,  16,  81, 256], dtype=int32)

In [10]:
b = np.arange(6,10)
b

array([6, 7, 8, 9])

In [11]:
a+b

array([ 7,  9, 11, 13])

In [12]:
a**b

array([     1,    128,   6561, 262144], dtype=int32)

## 2D arrays

In [17]:
x = np.array(a).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [23]:
y = np.array(b).reshape(2,2)
y

array([[6, 7],
       [8, 9]])

In [24]:
x+y

array([[ 7,  9],
       [11, 13]])

In [25]:
x*y

array([[ 6, 14],
       [24, 36]])

In [26]:
x.dot(y)

array([[22, 25],
       [50, 57]])

# divide by 0

In [27]:
a/0

<ipython-input-27-deacdc4ccabc>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([inf, inf, inf, inf])