In [1]:
import numpy as np

a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
a[a<12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a[a[3]] =0

In [7]:
a

array([ 1,  2,  3,  4,  0,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
a[a%2 == 0]

array([ 2,  4,  0,  6,  8, 10, 12, 14])

In [9]:
a

array([ 1,  2,  3,  4,  0,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
a[a%2 == 0] =0

In [11]:
a

array([ 1,  0,  3,  0,  0,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [12]:
a>5
a

array([ 1,  0,  3,  0,  0,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [13]:
a>5

array([False, False, False, False, False, False,  True, False,  True,
       False,  True, False,  True, False,  True])