In [11]:
import numpy as np


### by taking list of lists


In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### by taking user inputs

In [3]:
row = int(input("no:of rows : "))
col = int(input("no:of cols : "))

matrix = []

for i in range(row):
    a=[]
    for j in range(col):
        val = int(input("enter the value : "))
        a.append(val)
    matrix.append(a)
    
arr = np.array(matrix)

for i in range(row):
    for j in range(col):
        print(arr[i,j],end=" ")
    print()
print(type(arr))

no:of rows : 2
no:of cols : 3
enter the value : 1
enter the value : 2
enter the value : 3
enter the value : 4
enter the value : 5
enter the value : 6
1 2 3 
4 5 6 
<class 'numpy.ndarray'>


In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(arr)

[[1 2 3]
 [4 5 6]]


### by using seed and reshape

In [6]:
import numpy as np

np.random.seed(11)

arr = np.random.randint(1,100,30).reshape(6,5)

arr

array([[26, 64, 81, 92, 82],
       [56, 14, 77, 34, 72],
       [83, 25, 93, 49, 33],
       [46,  5, 35, 13,  2],
       [75, 38, 85, 82, 92],
       [25, 18, 68, 71, 44]])

In [7]:
arr[-1:,-1:]

array([[44]])

In [8]:
arr[2:4,2:4]

array([[93, 49],
       [35, 13]])

In [9]:
arr[1:3,-1:]

array([[72],
       [33]])