In [1]:
import numpy as np

#### zeros

In [2]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [3]:
arr.dtype

dtype('float64')

In [7]:
my_arr=np.zeros((2,3))
my_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

#### ones

In [9]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [10]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

#### eye

In [11]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

#### diag

In [14]:
arr=np.diag([3,12,45,32])
arr

array([[ 3,  0,  0,  0],
       [ 0, 12,  0,  0],
       [ 0,  0, 45,  0],
       [ 0,  0,  0, 32]])

In [15]:
np.diag(arr)

array([ 3, 12, 45, 32])

#### randint

In [20]:
arr = np.random.randint(1,10,4)
arr

array([1, 7, 2, 5])

#### rand

In [22]:
arr = np.random.rand(5)
arr


array([0.65533503, 0.62300613, 0.17808499, 0.85669509, 0.31497929])

In [23]:
arr = np.random.rand(2,3)
arr

array([[0.86802896, 0.54646889, 0.03779869],
       [0.17428692, 0.23580603, 0.39983779]])