In [1]:
import numpy as np

arr = np.random.randint(1,100,12)
arr

array([93, 50, 16, 10, 72, 10, 12, 78, 99, 59, 69, 30])

In [11]:
arr.reshape(2,6)

array([[93, 50, 16, 10, 72, 10],
       [12, 78, 99, 59, 69, 30]])

In [12]:
arr.ndim

1

In [3]:
arr.reshape(3,4)

array([[93, 50, 16, 10],
       [72, 10, 12, 78],
       [99, 59, 69, 30]])

In [4]:
arr.reshape(4,3)

array([[93, 50, 16],
       [10, 72, 10],
       [12, 78, 99],
       [59, 69, 30]])

In [5]:
arr.reshape(6,2)

array([[93, 50],
       [16, 10],
       [72, 10],
       [12, 78],
       [99, 59],
       [69, 30]])

### concept of -1

In [6]:
arr.reshape(-1,4)

array([[93, 50, 16, 10],
       [72, 10, 12, 78],
       [99, 59, 69, 30]])

In [8]:
arr.reshape(6,-1)


array([[93, 50],
       [16, 10],
       [72, 10],
       [12, 78],
       [99, 59],
       [69, 30]])

In [9]:
arr.shape

(12,)

In [10]:
arr.ndim

1