In [10]:
import numpy as np

np.random.seed(12)
arr = np.random.randint(1,100,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [13]:
import numpy as np

np.random.seed(1)
arr = np.random.randint(1,100,10)
arr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [14]:
import numpy as np

np.random.seed(12)
arr = np.random.randint(1,100,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])