In [1]:
import numpy as np

### view

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9])
slicing = a[3:6]
slicing[:] = 0

a




array([1, 2, 3, 0, 0, 0, 7, 8, 9])

In [3]:
slicing

array([0, 0, 0])

### copy

In [5]:
slicing = a[3:6].copy()

slicing[:] = 1

slicing

array([1, 1, 1])

In [6]:
a

array([1, 2, 3, 0, 0, 0, 7, 8, 9])